### ISSUE TITLE
Interested to add types?

### ISSUE THREAD

**Issue by jdonnerstag** [fsspec/filesystem_spec#1114] opened 2022-11-12 17:49 UTC
I like types and if there is interest, I could start adding them. 
Any specific developer guides I need to follow?

**Comment by martindurant** [comment] 2022-11-12 18:16
There is, I think, an existing issue for this. 
I am not opposed, but there is no guide (since we don't have types yet) and many places where Any is the only reasonable options - which is no help at all. I wish you the best!

**Comment by yarikoptic** [comment] 2022-11-15 19:34
FWIW typing might have helped to prevent error exhibited itself in https://github.com/fsspec/filesystem_spec/issues/1107#issuecomment-1313988529

**Comment by ianthomas23** [comment] 2022-12-08 17:39
There are a number of issues about adding type annotations. I am closing this as a duplicate of #625 as that has the most relevant discussion.

**Closed by ianthomas23** 2022-12-08 17:39 UTC
