### ISSUE TITLE
[Feature Request] Typehints

### ISSUE THREAD

**Issue by alanhdu** [fsspec/filesystem_spec#834] opened 2021-11-22 21:06 UTC
Hi all! I was wondering whether `fsspec` would be open to adding typehints to its codebase (both for internal checking, and for packaging externally via PEP 561). This has a number of advantages (better IDE integration, might catch bugs, etc), so this is definitely something I think would improve the end-user experience.

If you're interested, I'd be happy to send along some patches setting up some of the infrastructure and starting to create some of the type annotations.

Let me know what you think!

**Comment by martindurant** [comment] 2021-11-22 21:09
I am not opposed to typehints in the repo, but I'm not likely to put in any effort myself to add them.

**Comment by alanhdu** [comment] 2021-11-22 21:33
> I am not opposed to typehints in the repo, but I'm not likely to put in any effort myself to add them.

That's ok! I can try and carve out some time at work to try and contribute some patches for this then.

**Comment by ianthomas23** [comment] 2022-12-08 17:39
There are a number of issues about adding type annotations. I am closing this as a duplicate of #625 as that has the most relevant discussion.

**Closed by ianthomas23** 2022-12-08 17:39 UTC
