### ISSUE TITLE
Add type annotations (PEP 484)

### ISSUE THREAD

**Issue by dargueta** [fsspec/filesystem_spec#451] opened 2020-10-14 18:53 UTC
For those of us using MyPy in our projects it'd be really helpful to add typing annotations. Now that we only support Python 3.6+ we can do this directly in the code instead of having to use comments. I'd be willing to take this on if owners are interested.

If we don't want to do this in the codebase here I could do it on typeshed but that's less than ideal.

(Probably required for https://github.com/dask/s3fs/issues/383)

**Comment by racinmat** [comment] 2022-10-27 14:00
I would really appreciate this.

**Comment by ianthomas23** [comment] 2022-12-08 17:38
There are a number of issues about adding type annotations. I am closing this as a duplicate of #625 as that has the most relevant discussion.

**Closed by ianthomas23** 2022-12-08 17:38 UTC
